version: "3.8"
services:
  db:
    image: "mysql:5.7" 
    restart: always
    environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_USERNAME: root
     MYSQL_PASSWORD: root
    expose:
      - '3306'
    volumes:
      - db:/var/run/mysqld
    logging:
            driver: none
    ports:
      - "3306:3306"
  redis:
    image: redis:4.0-alpine
    command: redis-server
    volumes:
      - redis:/data
    ports:
      - 6379
    logging:
            driver: none
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails db:migrate & bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
     DB_USERNAME: root
     DB_PASSWORD: root
     DB_NAME: blog_API
     DB_PORT: 3306
     DB_HOST: db
     RAILS_ENV: development
     RAILS_MAX_THREADS: 5
     REDIS_HOST: redis
     REDIS_PORT: 6379
     BUNDLE_PATH: /bundle
    volumes:
      - .:/myapp
      - bundle:/bundle
    ports:
      - "3000:3000"
    depends_on:
      - "db"
      - "redis"

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/myapp
    environment:
      RAILS_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - "redis"
volumes:
  db:
  bundle:
  redis: